### ISSUE TITLE
New logo/icon

### ISSUE THREAD

**Issue by mansya** [harshitbudhraja/LAN-Messenger#6]
Hi, I am a graphic designer, I want to help others in graphic design.

After I reviewed your project, you have no logo on this project. Therefore I want to contribute to this project by creating a new logo / icon. what do you think?

**Comment by ghost** [comment]
Hey @mansya !!! I'm glad you reviewed my project and would like to contribute to it...
Actually this project is quite old and is no longer maintained by me or anyone else...So, I don't think there is any point in investing your time in designing a logo for it...

Anyways, thanks a lot for getting in touch with me :) By the way, I do have an ongoing project which you could help me in, if you're interested...Ping me and let me know !!!

**Comment by mansya** [comment]
the offer would be great to me. I will review your other project.

**Comment by mansya** [comment]
I have design logo for this project. what do you think ? do you like it ?
![lan messsengerr](https://user-images.githubusercontent.com/33461607/43049109-79e831d2-8e1c-11e8-979c-bae280840f79.png)

Sorry for a long time :-)

**Comment by ghost** [comment]
The logo is too good @mansya, I loved it !!!! Maybe if the community reincarnates this project, we'll use this as the official logo :)

Btw, the other project that I'm talking about is on a private repository as of now. Share your mail address and I can tell you more about the project :)

**Comment by mansya** [comment]
Mansyaprime16@gmail.com 

I will create a Pull Requests a few hours later.

**Comment by mansya** [comment]
I have upload all files to this link
https://drive.google.com/open?id=1TsNQdOLFkfBTSVqWVq4Dx4XsXTAtTJuf

and I have sent pull requests. please check it.
